# Introduction to Python Week One

Welcome to the Data Products, Services, and Governance division introduction to Python learning materials. These materials have been adapted from a classroom-based training series, so that they can be followed without additional teacher instruction as much as possible.

## Motivation

There are many reasons for taking part in introductory Python training: 
- It is directly needed for your role in the ONS e.g. you are a new DPSG apprentice and need to learn Python to get started with data engineering. 
- It maybe/ will be a part of your role in the future e.g. you currently use Excel/ SAS and there are discussions in your group about moving away from these tools towards an open-source solution.
- Your role requires no Python, but you suspect Python could be used to improve parts of your daily work e.g. You are looking to use Python to automate some part of your work process.
- Just because/ you’re just looking.

## Why create this training? 

There are a plethora of fantastic introductory Python training and data focussed training in the public domain. I wont list them all here, but some good examples of a general Python introduction are [freeCodeCamp](https://www.freecodecamp.org/) and [CS50P](https://www.youtube.com/playlist?list=PLhQjrBD2T3817j24-GogXmWqO5Q5vYy0V). These resources are fantastic and will provide a solid foundation in Python. Additionally, throughout this training series we reference several specific learning resources – specific either to data manipulation, a civil service context or an ONS context. 

The purpose of this training series is to create a short, public, beginner friendly collection of teaching resources that are relevant specifically to ONS colleagues who are looking to use Python to work with data but that also caters to all the motivated learners mentioned above. 

## What is coding and why Python?

Coding is simply a way of communicating with computers using languages they can understand. By writing code, we give computers precise instructions to follow in order to solve problems or automate tasks. TODO insclude explanation of abstraction???

There are many different programming languages, each with its own strengths and weaknesses. So why have we chosen Python?

- Python is sometimes described as the “second‑best language at everything”. It may not always be the optimal choice for highly specialised tasks (such as large-scale web applications or high-performance video games), but it is flexible enough to do all of these things reasonably well.
- Python is free and open source, with a large global community contributing libraries and extensions.
- Because of this large community, there is an enormous amount of online support, documentation, and training material available.
- Python is available on multiple ONS platforms, such as DAP and IDS.
- It is particularly well suited to data engineering and data science, with powerful libraries for data manipulation, analysis, and visualisation.
- Unlike some other languages or data manipulation tools, Python has well‑established testing frameworks, and results produced by Python scripts are generally easy to reproduce, which is essential for reliable analysis.

## Working with Jupyter Notebooks

The training materials are notebooks**, which allow us to combine written explanations, code, and outputs in a single interactive document.

### Cells

A Jupyter notebook is made up of **cells**. Each cell is a container that can hold either text or code, and cells are executed individually.

There are two main cell types you’ll encounter:

- **Markdown cells**  
  These cells contain formatted text, such as explanations, headings, bullet points, and links. They are used to describe concepts or provide instructions and do not run any code. This cell is a markdown cell.

- **Code cells**  
  These cells contain Python code. When you run a code cell, Python executes the code and displays the output directly below the cell (for example, printed text, tables, or charts).

You can switch a cell’s type using the toolbar or keyboard shortcuts, and you can add, delete, or reorder cells as needed.

### Running Cells and Execution Order

One important thing to understand about Jupyter notebooks is that **the order in which cells are run matters**.

- Code cells do **not** have to be run from top to bottom.
- When a cell is run, any variables, functions, or imports it creates are stored in memory.
- If you try to use something that hasn’t been defined yet — or was defined in a cell that hasn’t been run — you may see errors.

Because of this, running cells out of order can sometimes cause confusing or unexpected behaviour.

### Restarting the Kernel

The **kernel** is the process that runs your Python code and keeps track of everything currently stored in memory.

If you encounter a problem such as:
- Variables behaving unexpectedly
- Errors that don’t seem to make sense
- Code that worked before but no longer does

a common and effective solution is to:

**Restart the kernel and run all cells**

You can usually do this from the menu:  
`Kernel → Restart Kernel and Run All`

# Using Python as a Calculator

One of the easiest ways to get started with Python is to use it like a **calculator**. Python can perform basic arithmetic such as addition, subtraction, multiplication, and division, as well as more complex expressions using brackets. For example, Python understands expressions like `2 + 2` or `2 * (3 + 2)` and will return the result when you run the cell.

Below is an example code cell demonstrating this.  
**Try editing the numbers or the calculation yourself and re-run the cell** to see how the output changes. Experimenting like this is a great way to build confidence and understand how Python evaluates expressions.

In [2]:
2+2

4

## Introduction to Data Types

In the previous section, you used Python as a calculator to perform calculations like `2 + 2` or `2 * (3 + 2)`. Although it may not have been obvious at the time, you were already working with **data types**.

A **data type** describes the kind of data a value represents, and it determines what you can do with that value.

### Integers (`int`) and Floating‑Point Numbers (`float`)

- An **integer** (`int`) is a whole number, such as `1`, `10`, or `-3`.
- A **floating‑point number** (`float`) is a number with a decimal point, such as `3.14`, `0.5`, or `2.0`.

### Strings (`str`)
Another common and very important data type is the string (`str`).
A string represents text, such as words or sentences, and is created by enclosing characters in quotes:
- "Hello"
- 'Python'
- "1"

In [4]:
"Hello" + '100'

'Hello100'

## Assigning Values to Variables

So far, you’ve been working directly with values like numbers and text. In Python, we often want to **store values** so we can reuse them later. We do this by **assigning values to variables**.

A variable is simply a **name** that refers to a value in memory.

### Assigning Variables

You assign a value to a variable using the equals sign (`=`):

In [5]:
a = 1
b = "hello"

In [6]:
a

1

In [7]:
b

'hello'

Hint: Earlier we mentioned how the running order of cells is important. Try adding a cell below the one where we assign a, assigning it a different value such as `2`. Then rerun teh cell containing `a`. What prints?

In [1]:
import pandas as pd

C:\Users\lawrem1\Anaconda3\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(

In [8]:
df = pd.read_csv('2011.csv', header = 1)

In [10]:
df.head()

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,7394816,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4
1,7394745,E12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3
2,7395066,E12000001,H,3,1,2,4,1,2,1,1,1,1,1,6,11,3,4
3,7395329,E12000001,H,3,1,2,2,1,2,1,2,1,2,1,7,7,3,2
4,7394712,E12000001,H,3,1,1,5,4,2,1,1,1,2,1,1,4,3,2

In [11]:
df.tail()

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
569736,7946020,W92000004,H,1,1,1,5,1,2,1,4,1,9,1,8,8,3,3
569737,7944310,W92000004,H,3,1,1,3,1,2,1,2,1,1,1,7,4,3,4
569738,7945374,W92000004,H,3,1,1,1,1,1,1,1,1,2,-9,-9,-9,-9,-9
569739,7944768,W92000004,H,1,1,2,8,5,2,1,3,1,9,5,9,2,-9,4
569740,7944959,W92000004,H,2,1,2,2,2,2,1,2,1,1,1,7,4,1,4

In [14]:
df.shape

(569741, 18)

In [15]:
df.describe()

,Person ID,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
count,5.697410e+05,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000
mean,7.679353e+06,2.011870,1.018731,1.507550,3.978680,1.856201,1.777904,1.016239,1.658324,1.191250,2.419387,0.685597,1.240994,2.459844,-3.487095,0.034130
std,1.644702e+05,2.358788,0.159058,0.499943,2.219494,1.125020,0.415655,1.153095,1.486598,1.391858,2.493064,5.265465,6.521825,7.398945,5.887539,4.862672
min,7.394483e+06,-9.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,7.536918e+06,2.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-9.000000,-9.000000,-9.000000,1.000000
50%,7.679353e+06,2.000000,1.000000,2.000000,4.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,1.000000,3.000000,4.000000,-9.000000,2.000000
75%,7.821788e+06,3.000000,1.000000,2.000000,6.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,5.000000,6.000000,8.000000,3.000000,3.000000
max,7.964223e+06,6.000000,3.000000,2.000000,8.000000,5.000000,2.000000,2.000000,5.000000,5.000000,9.000000,9.000000,9.000000,12.000000,4.000000,4.000000