# Introduction to Python Week One

Welcome to the Data Products, Services, and Governance division introduction to Python learning materials. These materials have been adapted from a classroom-based training series. Adapted so that they can be followed without additional teacher instruction as much as possible.

There are many reasons for taking part in introductory Python training: 
- It is directly needed for your role in the ONS e.g. you are a new DPSG apprentice and need to learn Python to get started with data engineering. 
- It maybe/ will be a part of your role in the future e.g. you currently use Excel/ SAS and there are discussions in your group about moving away from these tools towards an open-source solution.
- Your role requires no Python, but you suspect Python could be used to improve parts of your daily work e.g. You are looking to use Python to automate soma part of your work process.
- Just because/ you’re just looking.

There are a plethora of fantastic introductory Python training and data focussed training in the public domain. I wont list them all here, but some good examples of a general Python introduction are [freeCodeCamp](https://www.freecodecamp.org/) and [CS50P](https://www.youtube.com/playlist?list=PLhQjrBD2T3817j24-GogXmWqO5Q5vYy0V). These resources are fantastic and will provide a solid foundation in Python. Additionally, throughout this training series we reference several specific learning resources – specific either to data manipulation, a civil service context or an ONS context. 

The purpose of this training series is to create a short, public, beginner friendly collection of teaching resources that are relevant specifically to ONS colleagues who are looking to use Python to work with data but that also caters to all the motivated learners mentioned above.

In [1]:
import pandas as pd

C:\Users\lawrem1\Anaconda3\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(

In [8]:
df = pd.read_csv('2011.csv', header = 1)

In [10]:
df.head()

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,7394816,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4
1,7394745,E12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3
2,7395066,E12000001,H,3,1,2,4,1,2,1,1,1,1,1,6,11,3,4
3,7395329,E12000001,H,3,1,2,2,1,2,1,2,1,2,1,7,7,3,2
4,7394712,E12000001,H,3,1,1,5,4,2,1,1,1,2,1,1,4,3,2

In [11]:
df.tail()

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
569736,7946020,W92000004,H,1,1,1,5,1,2,1,4,1,9,1,8,8,3,3
569737,7944310,W92000004,H,3,1,1,3,1,2,1,2,1,1,1,7,4,3,4
569738,7945374,W92000004,H,3,1,1,1,1,1,1,1,1,2,-9,-9,-9,-9,-9
569739,7944768,W92000004,H,1,1,2,8,5,2,1,3,1,9,5,9,2,-9,4
569740,7944959,W92000004,H,2,1,2,2,2,2,1,2,1,1,1,7,4,1,4

In [14]:
df.shape

(569741, 18)

In [15]:
df.describe()

,Person ID,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
count,5.697410e+05,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000
mean,7.679353e+06,2.011870,1.018731,1.507550,3.978680,1.856201,1.777904,1.016239,1.658324,1.191250,2.419387,0.685597,1.240994,2.459844,-3.487095,0.034130
std,1.644702e+05,2.358788,0.159058,0.499943,2.219494,1.125020,0.415655,1.153095,1.486598,1.391858,2.493064,5.265465,6.521825,7.398945,5.887539,4.862672
min,7.394483e+06,-9.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,7.536918e+06,2.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-9.000000,-9.000000,-9.000000,1.000000
50%,7.679353e+06,2.000000,1.000000,2.000000,4.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,1.000000,3.000000,4.000000,-9.000000,2.000000
75%,7.821788e+06,3.000000,1.000000,2.000000,6.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,5.000000,6.000000,8.000000,3.000000,3.000000
max,7.964223e+06,6.000000,3.000000,2.000000,8.000000,5.000000,2.000000,2.000000,5.000000,5.000000,9.000000,9.000000,9.000000,12.000000,4.000000,4.000000